remote_theme: "mmistakes/minimal-mistakes@4.28.1"

minimal_mistakes_skin: "dark"

title: "Thomas Sirchi"
name: "Thomas Sirchi"

description: >-
  Computational biologist working in cancer genomics,
  transcriptomics, single-cell and multi-omics.

url: "https://thokas99.github.io"
repository: "Thokas99/Thokas99.github.io"

atom_feed:
  hide: true

author:
  name: "Thomas Sirchi"
  avatar: "/assets/images/profile.jpg"
  bio: "Computational Biologist | Cancer genomics · Single-cell · Multi-omics"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Thokas99"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:thomasirchi@gmail.com"

plugins:
  - jekyll-include-cache
